src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $FullName;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\User", inversedBy="users")
     */
    private $amis;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\User", mappedBy="amis")
     */
    private $users;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Tweet", mappedBy="user")
     */
    private $Tweets;

    public function __construct()
    {
        $this->amis = new ArrayCollection();
        $this->users = new ArrayCollection();
        $this->Tweets = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFullName(): ?string
    {
        return $this->FullName;
    }

    public function setFullName(string $FullName): self
    {
        $this->FullName = $FullName;

        return $this;
    }

    /**
     * @return Collection|self[]
     */
    public function getAmis(): Collection
    {
        return $this->amis;
    }

    public function addAmi(self $ami): self
    {
        if (!$this->amis->contains($ami)) {
            $this->amis[] = $ami;
        }

        return $this;
    }

    public function removeAmi(self $ami): self
    {
        if ($this->amis->contains($ami)) {
            $this->amis->removeElement($ami);
        }

        return $this;
    }

    /**
     * @return Collection|self[]
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(self $user): self
    {
        if (!$this->users->contains($user)) {
            $this->users[] = $user;
            $user->addAmi($this);
        }

        return $this;
    }

    public function removeUser(self $user): self
    {
        if ($this->users->contains($user)) {
            $this->users->removeElement($user);
            $user->removeAmi($this);
        }

        return $this;
    }

    /**
     * @return Collection|Tweet[]
     */
    public function getTweets(): Collection
    {
        return $this->Tweets;
    }

    public function addTweet(Tweet $tweet): self
    {
        if (!$this->Tweets->contains($tweet)) {
            $this->Tweets[] = $tweet;
            $tweet->setUser($this);
        }

        return $this;
    }

    public function removeTweet(Tweet $tweet): self
    {
        if ($this->Tweets->contains($tweet)) {
            $this->Tweets->removeElement($tweet);
            // set the owning side to null (unless already changed)
            if ($tweet->getUser() === $this) {
                $tweet->setUser(null);
            }
        }

        return $this;
    }
}

src/Controller/SecurityController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;

class SecurityController extends AbstractController
{
    /**
     * @Route("/login", name="app_login")
     */
    public function login(AuthenticationUtils $authenticationUtils): Response
    {
        if($this->isGranted("IS_AUTHENTICATED_FULLY"))
        {
            return $this->redirectToRoute("profile");
        }

        // get the login error if there is one
        $error = $authenticationUtils->getLastAuthenticationError();
        // last username entered by the user
        $lastUsername = $authenticationUtils->getLastUsername();

        return $this->render('security/login.html.twig', ['last_username' => $lastUsername, 'error' => $error]);
    }

    /**
     * @Route("/logout", name="app_logout")
     */
    public function logout()
    {
        throw new \Exception('This method can be blank - it will be intercepted by the logout key on your firewall');
    }
}

templates/security/accueil.html.twig
{% extends 'base.html.twig' %}
{% block title 'Accueil' %}
{% block body %}
    <div class="container">

            {{ form_start(tweetform) }}
            {{ form_row(tweetform.content) }}
            <button class="btn btn-primary" type="submit">Post</button>
            {{ form_end(tweetform) }}

        <table class="container-fluid mt-5">
            {% for user in users %}
                       {% for tweet in user.tweets %}
        <div class="container-fluid mt-5">
                <p>
                <h4>{{ tweet.user.FullName }}</h4>{{ tweet.content }}
            </p>
        <hr>
        </div>
                {% endfor %}
                <tr><td>
                        {% if app.user != user %}
                        <div class="col-4">
                        <form method="post">
                            <div class="container">
                            <p class="h6">{{ user.FullName }}</p>
                            {% if user not in app.user.Amis %}
                                <a type="submit" class="btn btn-secondary" href="{{ path('addami', {'id':user.id}) }}">Add Friend</a></div>
                                {% else %}
                               Friend
                            {% endif %}
                        </form>
                        </div>
                        {% endif %}
                    </td>
                </tr>
            {% else %}
                <td> Empty </td>
            {% endfor %}
        </table>
    </div>
{% endblock %}

templates/security/amis.html.twig
{% extends 'base.html.twig' %}
{% block title 'Amis' %}
{% block body %}
    <div class="container">
        <table class="container-fluid mt-5">
            <h1></h1>
            {% for ami in amis %}
            <tr><td><p class="h4">{{ ami.FullName }}</p></td></tr>
                {% else %}
                <td> Empty </td>

            {% endfor %}
        </table>
    </div>
{% endblock %}

templates/security/login.html.twig
{% extends 'base.html.twig' %}

{% block title %}Log in!{% endblock %}

{% block body %}
<div class="row">
   <div class="col-6 offset-3">
       <form method="post">
           {% if error %}
               <div class="alert alert-danger">{{ error.messageKey|trans(error.messageData, 'security') }}</div>
           {% endif %}

           <div class="card">
               <div class="card-body bg-light">
               <h1 class="h3 mb-3 font-weight-normal text-center">Log In</h1>
                   <div class="form-group">
                       <label for="inputEmail" class="sr-only">Email</label>
                       <input type="email" value="{{ last_username }}" name="email" id="inputEmail" class="form-control" placeholder="Email" required autofocus>
                   </div>

                   <div class="form-group">
                       <label for="inputPassword" class="sr-only">Password</label>
                       <input type="password" name="password" id="inputPassword" class="form-control" placeholder="Password" required>
                   </div>

                   <input type="hidden" name="_csrf_token"
                       value="{{ csrf_token('authenticate') }}"
                   >

                   {#
                       Uncomment this section and add a remember_me option below your firewall to activate remember me functionality.
                       See https://symfony.com/doc/current/security/remember_me.html

                       <div class="checkbox mb-3">
                           <label>
                               <input type="checkbox" name="_remember_me"> Remember me
                           </label>
                       </div>
                   #}

                   <button class="btn btn-lg btn-primary btn-block" type="submit">
                       Log in
                   </button>
               </div>
           </div>
       </form>
   </div>
</div>
{% endblock %}

templates/security/profile.html.twig
{% extends 'base.html.twig' %}
{% block title user.FullName|upper %}
{% block body %}
    <div class="container">
            <h3 class="container-fluid mt-5">
                {{ user.FullName | upper }}
                <small class="text-muted">Profile</small>
            </h3>
        {% for tweet in app.user.tweets %}
                <div class="container-fluid mt-5">
                    <p>
                    <h4>{{ tweet.user.FullName }}</h4>{{ tweet.content }}
                    </p>
                    <hr>
                </div>
        {% endfor %}
    </div>
{% endblock %}